### ISSUE TITLE
Ruby 1.8.7 with rails 2.3.8

### ISSUE THREAD

**Issue by ghost** [zencephalon/Tactful_Tokenizer#3]
I am using the following method in my rails application's helper:

  require "rubygems"
  require "tactful_tokenizer"
  def split_sentences(text)
    m = TactfulTokenizer::Model.new
    m.tokenize_text(text)
  end

On execution, I am getting the following error:
undefined class/module ._She;

C:/Ruby187/lib/ruby/gems/1.8/gems/tactful_tokenizer-0.0.2/lib/tactful_tokenizer.rb:55:in `load'
C:/Ruby187/lib/ruby/gems/1.8/gems/tactful_tokenizer-0.0.2/lib/tactful_tokenizer.rb:55:in`initialize'
C:/Ruby187/lib/ruby/gems/1.8/gems/tactful_tokenizer-0.0.2/lib/tactful_tokenizer.rb:54:in `open'
C:/Ruby187/lib/ruby/gems/1.8/gems/tactful_tokenizer-0.0.2/lib/tactful_tokenizer.rb:54:in`initialize'
C:/Ruby187/lib/ruby/gems/1.8/gems/tactful_tokenizer-0.0.2/lib/tactful_tokenizer.rb:53:in `map'
C:/Ruby187/lib/ruby/gems/1.8/gems/tactful_tokenizer-0.0.2/lib/tactful_tokenizer.rb:53:in`initialize'
........
........

Can it be fixed?

**Comment by ghost** [comment]
Hm, it appears there is a problem with the Marshal library. '._She' is one of the Bayesian probability features stored in the dump, but Ruby seems to be interpreting it as a class or a module. Somehow Marshal on Windows isn't interpreting the data correctly it would seem. I'll see if I can figure out what the issue is.
